"""Patch gpu_finops_lab.ipynb: implement Part 8.5 TODO exercises (cells 37-41)."""
import json

NB_PATH = r"d:\Projects\VinUni_AI\Day25-Lab-GPU-FinOps-Cost_Optimization\notebook\gpu_finops_lab.ipynb"

# ── Cell 37: analyze_multi_gpu_cost ──────────────────────────────────────────
CELL_37 = (
    "# Cell 27: Multi-GPU Cost Analysis\n"
    "print('=' * 60)\n"
    "print('EXERCISE 8.5.1: Multi-GPU Cost Analysis')\n"
    "print('=' * 60)\n"
    "\n"
    "import numpy as np\n"
    "\n"
    "def analyze_multi_gpu_cost(base_time_hours, gpu_type, gpu_counts, scaling_factors=None):\n"
    "    price_per_hour = GPU_PRICING.get(gpu_type, 0.35)\n"
    "    default_efficiency = {1: 1.0, 2: 0.90, 4: 0.78, 8: 0.65, 16: 0.52}\n"
    "    if scaling_factors is None:\n"
    "        scaling_factors = {n: default_efficiency.get(n, max(0.4, 1.0 - 0.07 * n))\n"
    "                           for n in gpu_counts}\n"
    "    results = []\n"
    "    for n in gpu_counts:\n"
    "        eff = scaling_factors.get(n, 1.0)\n"
    "        speedup = n * eff\n"
    "        time_h = base_time_hours / speedup\n"
    "        cost = time_h * price_per_hour * n\n"
    "        cost_per_perf = cost / (base_time_hours / time_h)\n"
    "        results.append({'gpu_count': n, 'efficiency': eff, 'speedup': speedup,\n"
    "                         'time_hours': time_h, 'total_cost_usd': cost,\n"
    "                         'cost_per_speedup_unit': cost_per_perf})\n"
    "    optimal = min(results, key=lambda r: r['cost_per_speedup_unit'])\n"
    "    return {'gpu_type': gpu_type, 'base_time_hours': base_time_hours,\n"
    "            'price_per_hour': price_per_hour, 'results': results,\n"
    "            'optimal_gpu_count': optimal['gpu_count']}\n"
    "\n"
    "\n"
    "base_training_time = 2.0\n"
    "test_gpu_counts = [1, 2, 4, 8]\n"
    "\n"
    "analysis = analyze_multi_gpu_cost(base_training_time, detected_type, test_gpu_counts)\n"
    "\n"
    "print(f\"\\nGPU Type: {analysis['gpu_type']}  |  Base time: {analysis['base_time_hours']}h  \"\n"
    "      f\"|  Price: ${analysis['price_per_hour']:.2f}/hr\")\n"
    "print()\n"
    "print(f\"{'GPU Count':<12} {'Speedup':<10} {'Time (h)':<12} {'Total Cost':<14} {'Cost/SpeedupUnit'}\")\n"
    "print('-' * 68)\n"
    "for r in analysis['results']:\n"
    "    marker = ' <- OPTIMAL' if r['gpu_count'] == analysis['optimal_gpu_count'] else ''\n"
    "    print(f\"{r['gpu_count']:<12} {r['speedup']:<10.2f} {r['time_hours']:<12.2f} \"\n"
    "          f\"${r['total_cost_usd']:<13.2f} ${r['cost_per_speedup_unit']:.2f}{marker}\")\n"
    "print(f\"\\nOptimal GPU count for cost efficiency: {analysis['optimal_gpu_count']} GPUs\")\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "gpu_counts_plot = [r['gpu_count'] for r in analysis['results']]\n"
    "costs_plot      = [r['total_cost_usd'] for r in analysis['results']]\n"
    "speedups_plot   = [r['speedup'] for r in analysis['results']]\n"
    "\n"
    "axes[0].plot(gpu_counts_plot, costs_plot, 'b-o', linewidth=2, markersize=8, label='Actual cost')\n"
    "opt_idx = gpu_counts_plot.index(analysis['optimal_gpu_count'])\n"
    "axes[0].scatter([gpu_counts_plot[opt_idx]], [costs_plot[opt_idx]],\n"
    "                color='gold', s=200, zorder=5, label=f\"Optimal ({analysis['optimal_gpu_count']} GPUs)\")\n"
    "axes[0].set_xlabel('GPU Count'); axes[0].set_ylabel('Total Cost (USD)')\n"
    "axes[0].set_title('Multi-GPU Cost Curve'); axes[0].legend(); axes[0].grid(True, alpha=0.3)\n"
    "\n"
    "axes[1].plot(gpu_counts_plot, speedups_plot, 'g-o', linewidth=2, markersize=8, label='Actual speedup')\n"
    "axes[1].plot(gpu_counts_plot, gpu_counts_plot, 'r--', linewidth=1.5, label='Ideal (linear)')\n"
    "axes[1].set_xlabel('GPU Count'); axes[1].set_ylabel('Speedup Factor')\n"
    "axes[1].set_title('Scaling Efficiency'); axes[1].legend(); axes[1].grid(True, alpha=0.3)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('multi_gpu_scaling.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: multi_gpu_scaling.png')\n"
)

# ── Cell 38: forecast_project_cost ───────────────────────────────────────────
CELL_38 = (
    "# Cell 28: Project Cost Forecasting\n"
    "print('=' * 60)\n"
    "print('EXERCISE 8.5.2: Project Cost Forecasting')\n"
    "print('=' * 60)\n"
    "\n"
    "import math\n"
    "\n"
    "def forecast_project_cost(phases, contingency_pct=20, confidence_level=0.95):\n"
    "    phase_results = []\n"
    "    total_base = 0.0\n"
    "    total_variance = 0.0\n"
    "    for ph in phases:\n"
    "        price = GPU_PRICING.get(ph['gpu_type'], 0.35)\n"
    "        base_cost = ph['duration_hours'] * price * ph['gpu_count']\n"
    "        uncertainty = base_cost * ph['uncertainty_pct']\n"
    "        phase_results.append({'name': ph['name'], 'gpu_type': ph['gpu_type'],\n"
    "                               'gpu_count': ph['gpu_count'],\n"
    "                               'duration_hours': ph['duration_hours'],\n"
    "                               'base_cost': base_cost, 'uncertainty': uncertainty})\n"
    "        total_base += base_cost\n"
    "        total_variance += uncertainty ** 2\n"
    "    total_std = math.sqrt(total_variance)\n"
    "    contingency = total_base * (contingency_pct / 100)\n"
    "    expected_total = total_base + contingency\n"
    "    z = {0.90: 1.645, 0.95: 1.960, 0.99: 2.576}.get(confidence_level, 1.960)\n"
    "    ci_margin = z * total_std\n"
    "    return {'phases': phase_results, 'total_base_cost': total_base,\n"
    "            'contingency': contingency, 'expected_total': expected_total,\n"
    "            'ci_lower': max(0, expected_total - ci_margin),\n"
    "            'ci_upper': expected_total + ci_margin,\n"
    "            'confidence_level': confidence_level, 'total_std': total_std}\n"
    "\n"
    "\n"
    "example_project = [\n"
    "    {'name': 'Data Preparation',      'gpu_type': 'T4',   'gpu_count': 1, 'duration_hours': 40,  'uncertainty_pct': 0.15},\n"
    "    {'name': 'Model Training',         'gpu_type': 'A100', 'gpu_count': 4, 'duration_hours': 120, 'uncertainty_pct': 0.25},\n"
    "    {'name': 'Hyperparameter Tuning',  'gpu_type': 'A100', 'gpu_count': 8, 'duration_hours': 60,  'uncertainty_pct': 0.30},\n"
    "    {'name': 'Model Evaluation',       'gpu_type': 'T4',   'gpu_count': 2, 'duration_hours': 20,  'uncertainty_pct': 0.10},\n"
    "]\n"
    "\n"
    "fc = forecast_project_cost(example_project)\n"
    "\n"
    "print(f\"\\n{'Phase':<28} {'GPU':<6} {'Count':<7} {'Hours':<8} {'Base Cost':<14} {'+-Uncertainty'}\")\n"
    "print('-' * 75)\n"
    "for ph in fc['phases']:\n"
    "    print(f\"{ph['name']:<28} {ph['gpu_type']:<6} {ph['gpu_count']:<7} \"\n"
    "          f\"{ph['duration_hours']:<8} ${ph['base_cost']:<13,.2f} +-${ph['uncertainty']:.2f}\")\n"
    "print()\n"
    "print(f\"  Total base cost:            ${fc['total_base_cost']:,.2f}\")\n"
    "print(f\"  Contingency (20%):          ${fc['contingency']:,.2f}\")\n"
    "print(f\"  Expected total:             ${fc['expected_total']:,.2f}\")\n"
    "print(f\"  95% CI:  [${fc['ci_lower']:,.2f}  -  ${fc['ci_upper']:,.2f}]\")\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "phase_names = [ph['name'] for ph in fc['phases']]\n"
    "phase_costs = [ph['base_cost'] for ph in fc['phases']]\n"
    "colors = ['#2196F3', '#FF9800', '#F44336', '#4CAF50']\n"
    "bars = axes[0].bar(range(len(phase_names)), phase_costs, color=colors)\n"
    "axes[0].set_xticks(range(len(phase_names)))\n"
    "axes[0].set_xticklabels(phase_names, rotation=20, ha='right', fontsize=9)\n"
    "axes[0].set_ylabel('Cost (USD)'); axes[0].set_title('Phase-by-Phase Cost Breakdown')\n"
    "for bar, cost in zip(bars, phase_costs):\n"
    "    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,\n"
    "                 f'${cost:,.0f}', ha='center', va='bottom', fontsize=9)\n"
    "\n"
    "scenarios = ['Best Case', 'Expected', 'Worst Case']\n"
    "values = [fc['ci_lower'], fc['expected_total'], fc['ci_upper']]\n"
    "bar_colors = ['#4CAF50', '#2196F3', '#F44336']\n"
    "bars2 = axes[1].bar(scenarios, values, color=bar_colors, width=0.5)\n"
    "axes[1].axhline(y=fc['total_base_cost'], color='gray', linestyle='--', linewidth=1.5, label='Base cost')\n"
    "axes[1].set_ylabel('Total Cost (USD)'); axes[1].set_title('Project Cost Forecast (95% CI)')\n"
    "axes[1].legend()\n"
    "for bar, val in zip(bars2, values):\n"
    "    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 20,\n"
    "                 f'${val:,.0f}', ha='center', va='bottom', fontsize=10, fontweight='bold')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('project_forecast.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: project_forecast.png')\n"
)

# ── Cell 39: analyze_optimization_opportunities ──────────────────────────────
CELL_39 = (
    "# Cell 29: Optimization Opportunity Analysis\n"
    "print('=' * 60)\n"
    "print('EXERCISE 8.5.3: Advanced Optimization Opportunity Analysis')\n"
    "print('=' * 60)\n"
    "\n"
    "EFFORT_SCORE = {'LOW': 1, 'MEDIUM': 2, 'HIGH': 3}\n"
    "RISK_SCORE   = {'LOW': 1, 'MEDIUM': 2, 'HIGH': 3}\n"
    "\n"
    "def analyze_optimization_opportunities(current_config, optimization_strategies):\n"
    "    price = GPU_PRICING.get(current_config['gpu_type'], 0.35)\n"
    "    baseline_cost = current_config['duration_hours'] * price * current_config['gpu_count']\n"
    "    scored = []\n"
    "    for strat in optimization_strategies:\n"
    "        savings_usd = baseline_cost * strat['savings_pct']\n"
    "        effort = EFFORT_SCORE[strat['implementation_effort']]\n"
    "        risk   = RISK_SCORE[strat['risk_level']]\n"
    "        priority_score = strat['savings_pct'] / (effort * risk)\n"
    "        scored.append({**strat, 'savings_usd': savings_usd,\n"
    "                        'priority_score': priority_score,\n"
    "                        'effort_score': effort, 'risk_score': risk})\n"
    "    scored.sort(key=lambda x: x['priority_score'], reverse=True)\n"
    "    cumulative_cost = baseline_cost\n"
    "    roadmap = []\n"
    "    for rank, s in enumerate(scored, 1):\n"
    "        saving = cumulative_cost * s['savings_pct']\n"
    "        cumulative_cost -= saving\n"
    "        roadmap.append({**s, 'rank': rank,\n"
    "                         'cumulative_savings_usd': baseline_cost - cumulative_cost,\n"
    "                         'remaining_cost': cumulative_cost})\n"
    "    return {'baseline_cost': baseline_cost, 'strategies': roadmap,\n"
    "            'total_potential_savings': baseline_cost - cumulative_cost,\n"
    "            'total_savings_pct': (baseline_cost - cumulative_cost) / baseline_cost * 100}\n"
    "\n"
    "\n"
    "example_strategies = [\n"
    "    {'name': 'Switch to Mixed Precision (AMP)', 'savings_pct': 0.25, 'implementation_effort': 'LOW',    'risk_level': 'LOW',    'dependencies': []},\n"
    "    {'name': 'Use Spot Instances',              'savings_pct': 0.60, 'implementation_effort': 'MEDIUM', 'risk_level': 'HIGH',   'dependencies': []},\n"
    "    {'name': 'Optimize Batch Size',             'savings_pct': 0.15, 'implementation_effort': 'LOW',    'risk_level': 'LOW',    'dependencies': []},\n"
    "    {'name': 'Implement Early Stopping',        'savings_pct': 0.20, 'implementation_effort': 'MEDIUM', 'risk_level': 'LOW',    'dependencies': []},\n"
    "    {'name': 'Switch to More Efficient GPU',    'savings_pct': 0.40, 'implementation_effort': 'HIGH',   'risk_level': 'MEDIUM', 'dependencies': []},\n"
    "]\n"
    "\n"
    "current_training_config = {\n"
    "    'gpu_type': 'A100', 'gpu_count': 4, 'duration_hours': 100,\n"
    "    'precision': 'FP32', 'instance_type': 'on-demand',\n"
    "}\n"
    "\n"
    "result = analyze_optimization_opportunities(current_training_config, example_strategies)\n"
    "\n"
    "print(f\"\\nBaseline cost: ${result['baseline_cost']:,.2f}\")\n"
    "print()\n"
    "print(f\"{'Rank':<5} {'Strategy':<35} {'Savings%':<10} {'Savings$':<12} {'Effort':<8} {'Risk':<8} {'Priority'}\")\n"
    "print('-' * 90)\n"
    "for s in result['strategies']:\n"
    "    print(f\"{s['rank']:<5} {s['name']:<35} {s['savings_pct']*100:<10.1f} \"\n"
    "          f\"${s['savings_usd']:<11.2f} {s['implementation_effort']:<8} \"\n"
    "          f\"{s['risk_level']:<8} {s['priority_score']:.3f}\")\n"
    "print(f\"\\n  Total potential savings: ${result['total_potential_savings']:,.2f} \"\n"
    "      f\"({result['total_savings_pct']:.1f}%)\")\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "scatter_colors = {'LOW': '#4CAF50', 'MEDIUM': '#FF9800', 'HIGH': '#F44336'}\n"
    "from matplotlib.lines import Line2D\n"
    "for s in result['strategies']:\n"
    "    c = scatter_colors[s['risk_level']]\n"
    "    axes[0].scatter(s['effort_score'], s['savings_pct']*100, s=200, color=c, alpha=0.8, zorder=5)\n"
    "    axes[0].annotate(s['name'].split('(')[0].strip()[:20],\n"
    "                     (s['effort_score'], s['savings_pct']*100),\n"
    "                     textcoords='offset points', xytext=(5, 5), fontsize=8)\n"
    "legend_elements = [Line2D([0], [0], marker='o', color='w',\n"
    "                           markerfacecolor=v, markersize=10, label=k)\n"
    "                   for k, v in scatter_colors.items()]\n"
    "axes[0].legend(handles=legend_elements, title='Risk Level')\n"
    "axes[0].set_xlabel('Effort (1=Low, 3=High)'); axes[0].set_ylabel('Savings %')\n"
    "axes[0].set_title('Optimization Prioritization Matrix')\n"
    "axes[0].set_xticks([1, 2, 3]); axes[0].set_xticklabels(['Low', 'Medium', 'High'])\n"
    "axes[0].grid(True, alpha=0.3)\n"
    "\n"
    "strats = result['strategies']\n"
    "names_short = [s['name'].split('(')[0][:22] for s in strats]\n"
    "cum_savings = [s['cumulative_savings_usd'] for s in strats]\n"
    "axes[1].bar(range(len(strats)), cum_savings, color='#2196F3')\n"
    "axes[1].set_xticks(range(len(strats)))\n"
    "axes[1].set_xticklabels(names_short, rotation=30, ha='right', fontsize=8)\n"
    "axes[1].axhline(y=result['baseline_cost']*0.5, color='orange', linestyle='--', label='50% target')\n"
    "axes[1].set_ylabel('Cumulative Savings (USD)'); axes[1].set_title('Optimization Roadmap')\n"
    "axes[1].legend()\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('optimization_roadmap.png', dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: optimization_roadmap.png')\n"
)

# ── Cell 40: create_advanced_finops_dashboard ────────────────────────────────
CELL_40 = (
    "# Cell 30: Integrated Cost Dashboard\n"
    "print('=' * 60)\n"
    "print('EXERCISE 8.5.4: Integrated Cost Dashboard')\n"
    "print('=' * 60)\n"
    "\n"
    "def create_advanced_finops_dashboard(multi_gpu_analysis, project_forecast_result, optimization_result):\n"
    "    fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n"
    "\n"
    "    # Plot 1: Multi-GPU cost curve\n"
    "    gpu_counts = [r['gpu_count'] for r in multi_gpu_analysis['results']]\n"
    "    costs      = [r['total_cost_usd'] for r in multi_gpu_analysis['results']]\n"
    "    opt        = multi_gpu_analysis['optimal_gpu_count']\n"
    "    axes[0, 0].plot(gpu_counts, costs, 'b-o', linewidth=2, markersize=8)\n"
    "    opt_cost = next(r['total_cost_usd'] for r in multi_gpu_analysis['results'] if r['gpu_count'] == opt)\n"
    "    axes[0, 0].scatter([opt], [opt_cost], color='gold', s=250, zorder=6, label=f'Optimal ({opt} GPUs)')\n"
    "    axes[0, 0].set_xlabel('GPU Count'); axes[0, 0].set_ylabel('Total Cost (USD)')\n"
    "    axes[0, 0].set_title('Multi-GPU Cost Curve'); axes[0, 0].legend(); axes[0, 0].grid(True, alpha=0.3)\n"
    "\n"
    "    # Plot 2: Scaling efficiency\n"
    "    speedups = [r['speedup'] for r in multi_gpu_analysis['results']]\n"
    "    axes[0, 1].plot(gpu_counts, speedups, 'g-o', linewidth=2, markersize=8, label='Actual')\n"
    "    axes[0, 1].plot(gpu_counts, gpu_counts, 'r--', linewidth=1.5, label='Ideal (linear)')\n"
    "    axes[0, 1].fill_between(gpu_counts, speedups, gpu_counts, alpha=0.15, color='red', label='Efficiency gap')\n"
    "    axes[0, 1].set_xlabel('GPU Count'); axes[0, 1].set_ylabel('Speedup')\n"
    "    axes[0, 1].set_title('Scaling Efficiency'); axes[0, 1].legend(); axes[0, 1].grid(True, alpha=0.3)\n"
    "\n"
    "    # Plot 3: Project forecast\n"
    "    scenarios = ['Best Case', 'Expected', 'Worst Case']\n"
    "    values = [project_forecast_result['ci_lower'], project_forecast_result['expected_total'],\n"
    "              project_forecast_result['ci_upper']]\n"
    "    bar_colors = ['#4CAF50', '#2196F3', '#F44336']\n"
    "    bars = axes[0, 2].bar(scenarios, values, color=bar_colors, width=0.5, alpha=0.85)\n"
    "    axes[0, 2].axhline(y=project_forecast_result['total_base_cost'], color='gray',\n"
    "                        linestyle='--', linewidth=1.5, label='Base cost')\n"
    "    axes[0, 2].set_ylabel('Total Cost (USD)'); axes[0, 2].set_title('Project Forecast (95% CI)')\n"
    "    axes[0, 2].legend()\n"
    "    for bar, val in zip(bars, values):\n"
    "        axes[0, 2].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 20,\n"
    "                         f'${val:,.0f}', ha='center', va='bottom', fontsize=9, fontweight='bold')\n"
    "\n"
    "    # Plot 4: Phase cost pie\n"
    "    phase_names  = [ph['name'] for ph in project_forecast_result['phases']]\n"
    "    phase_costs  = [ph['base_cost'] for ph in project_forecast_result['phases']]\n"
    "    pie_colors = ['#2196F3', '#FF9800', '#F44336', '#4CAF50']\n"
    "    wedges, texts, autotexts = axes[1, 0].pie(\n"
    "        phase_costs, labels=phase_names, colors=pie_colors, autopct='%1.1f%%', startangle=90)\n"
    "    for at in autotexts:\n"
    "        at.set_fontsize(8)\n"
    "    axes[1, 0].set_title('Phase Cost Distribution')\n"
    "\n"
    "    # Plot 5: Optimization prioritization scatter\n"
    "    sc_colors = {'LOW': '#4CAF50', 'MEDIUM': '#FF9800', 'HIGH': '#F44336'}\n"
    "    from matplotlib.lines import Line2D\n"
    "    for s in optimization_result['strategies']:\n"
    "        c = sc_colors[s['risk_level']]\n"
    "        axes[1, 1].scatter(s['effort_score'], s['savings_pct']*100, s=200, color=c, alpha=0.85, zorder=5)\n"
    "        axes[1, 1].annotate(s['name'][:20],\n"
    "                             (s['effort_score'], s['savings_pct']*100),\n"
    "                             textcoords='offset points', xytext=(4, 4), fontsize=7)\n"
    "    legend_elements = [Line2D([0], [0], marker='o', color='w',\n"
    "                               markerfacecolor=v, markersize=10, label=k)\n"
    "                       for k, v in sc_colors.items()]\n"
    "    axes[1, 1].legend(handles=legend_elements, title='Risk', fontsize=8)\n"
    "    axes[1, 1].set_xlabel('Effort (1=Low, 3=High)'); axes[1, 1].set_ylabel('Savings %')\n"
    "    axes[1, 1].set_title('Optimization Priority Matrix')\n"
    "    axes[1, 1].set_xticks([1, 2, 3]); axes[1, 1].set_xticklabels(['Low', 'Medium', 'High'])\n"
    "    axes[1, 1].grid(True, alpha=0.3)\n"
    "\n"
    "    # Plot 6: Cumulative savings roadmap\n"
    "    strats = optimization_result['strategies']\n"
    "    names_short = [s['name'].split('(')[0][:20] for s in strats]\n"
    "    cum_savings = [s['cumulative_savings_usd'] for s in strats]\n"
    "    axes[1, 2].bar(range(len(strats)), cum_savings, color='#9C27B0', alpha=0.8)\n"
    "    axes[1, 2].axhline(y=optimization_result['baseline_cost'] * 0.5,\n"
    "                        color='orange', linestyle='--', linewidth=1.5, label='50% target')\n"
    "    axes[1, 2].set_xticks(range(len(strats)))\n"
    "    axes[1, 2].set_xticklabels(names_short, rotation=30, ha='right', fontsize=8)\n"
    "    axes[1, 2].set_ylabel('Cumulative Savings (USD)'); axes[1, 2].set_title('Optimization Roadmap')\n"
    "    axes[1, 2].legend(fontsize=8)\n"
    "\n"
    "    plt.suptitle('Advanced GPU FinOps Dashboard', fontsize=15, fontweight='bold', y=1.02)\n"
    "    plt.tight_layout()\n"
    "    plt.savefig('advanced_finops_dashboard.png', dpi=150, bbox_inches='tight')\n"
    "    plt.show()\n"
    "    return fig\n"
    "\n"
    "\n"
    "fig = create_advanced_finops_dashboard(analysis, fc, result)\n"
    "print('Saved: advanced_finops_dashboard.png')\n"
)

# ── Cell 41: Challenge Exercise ───────────────────────────────────────────────
CELL_41 = (
    "# Cell 31: Challenge Exercise - Cost Optimization Strategy Design\n"
    "print('=' * 60)\n"
    "print('CHALLENGE EXERCISE 8.5.5: Design Cost Optimization Strategy')\n"
    "print('=' * 60)\n"
    "\n"
    "challenge_scenario = {\n"
    "    'project': 'Large Language Model Fine-tuning',\n"
    "    'requirements': {\n"
    "        'training_duration': 200,\n"
    "        'gpu_type': 'A100',\n"
    "        'gpu_count': 8,\n"
    "        'precision': 'FP32',\n"
    "        'instance_type': 'on-demand',\n"
    "        'budget': 5000,\n"
    "    },\n"
    "    'constraints': {\n"
    "        'max_preemption_risk': 'MEDIUM',\n"
    "        'min_accuracy': 0.95,\n"
    "        'deadline': '2 weeks',\n"
    "    },\n"
    "}\n"
    "\n"
    "req = challenge_scenario['requirements']\n"
    "price = GPU_PRICING[req['gpu_type']]\n"
    "baseline_cost = req['training_duration'] * price * req['gpu_count']\n"
    "\n"
    "print(f\"\\nProject: {challenge_scenario['project']}\")\n"
    "print(f\"Baseline: {req['gpu_count']}x {req['gpu_type']} \"\n"
    "      f\"for {req['training_duration']}h  ->  ${baseline_cost:,.2f}\")\n"
    "print(f\"Budget:   ${req['budget']:,.2f}\")\n"
    "print(f\"Surplus/Deficit: ${req['budget'] - baseline_cost:,.2f}\")\n"
    "\n"
    "# Step 1: Multi-GPU analysis\n"
    "print('\\n--- Step 1: Multi-GPU Analysis ---')\n"
    "mg = analyze_multi_gpu_cost(req['training_duration'], req['gpu_type'], [1, 2, 4, 8, 16])\n"
    "for r in mg['results']:\n"
    "    m = ' <- OPTIMAL' if r['gpu_count'] == mg['optimal_gpu_count'] else ''\n"
    "    print(f\"  {r['gpu_count']} GPUs: {r['time_hours']:.1f}h  ${r['total_cost_usd']:,.2f}{m}\")\n"
    "\n"
    "opt_gpu = mg['optimal_gpu_count']\n"
    "opt_result_ch = next(r for r in mg['results'] if r['gpu_count'] == opt_gpu)\n"
    "\n"
    "# Step 2: Choose optimization strategies\n"
    "print('\\n--- Step 2: Selecting strategies (max_preemption_risk=MEDIUM) ---')\n"
    "savings_gpu_change = max(0.0, 1.0 - opt_result_ch['total_cost_usd'] / baseline_cost)\n"
    "challenge_strategies = [\n"
    "    {'name': 'Mixed Precision (AMP)',    'savings_pct': 0.25, 'implementation_effort': 'LOW',    'risk_level': 'LOW'},\n"
    "    {'name': 'Gradient Checkpointing',   'savings_pct': 0.10, 'implementation_effort': 'LOW',    'risk_level': 'LOW'},\n"
    "    {'name': 'Spot Instances (partial)', 'savings_pct': 0.35, 'implementation_effort': 'MEDIUM', 'risk_level': 'MEDIUM'},\n"
    "]\n"
    "if savings_gpu_change > 0.01:\n"
    "    challenge_strategies.append({'name': 'Optimal GPU count',\n"
    "                                  'savings_pct': savings_gpu_change,\n"
    "                                  'implementation_effort': 'MEDIUM', 'risk_level': 'LOW'})\n"
    "\n"
    "opt_config_ch = {'gpu_type': req['gpu_type'], 'gpu_count': opt_gpu,\n"
    "                  'duration_hours': opt_result_ch['time_hours']}\n"
    "opt_analysis_ch = analyze_optimization_opportunities(opt_config_ch, challenge_strategies)\n"
    "\n"
    "print(f\"  Baseline (optimal GPU config): ${opt_analysis_ch['baseline_cost']:,.2f}\")\n"
    "for s in opt_analysis_ch['strategies']:\n"
    "    print(f\"  [{s['rank']}] {s['name']}: {s['savings_pct']*100:.1f}%  \"\n"
    "          f\"(cumulative saved: ${s['cumulative_savings_usd']:,.2f})\")\n"
    "\n"
    "# Step 3: Forecast with uncertainty\n"
    "print('\\n--- Step 3: Cost Forecast ---')\n"
    "challenge_phases = [\n"
    "    {'name': 'LLM Fine-tuning',   'gpu_type': req['gpu_type'],\n"
    "     'gpu_count': opt_gpu, 'duration_hours': opt_result_ch['time_hours'], 'uncertainty_pct': 0.20},\n"
    "    {'name': 'Eval & Validation', 'gpu_type': 'T4',\n"
    "     'gpu_count': 2, 'duration_hours': opt_result_ch['time_hours'] * 0.1, 'uncertainty_pct': 0.10},\n"
    "]\n"
    "challenge_fc = forecast_project_cost(challenge_phases, contingency_pct=15)\n"
    "final_expected = challenge_fc['expected_total'] * (1 - opt_analysis_ch['total_savings_pct'] / 100)\n"
    "\n"
    "print(f\"  Expected total (with optimizations): ${final_expected:,.2f}\")\n"
    "print(f\"  95% CI: [${challenge_fc['ci_lower']:,.2f}  -  ${challenge_fc['ci_upper']:,.2f}]\")\n"
    "\n"
    "# Step 4: Budget check\n"
    "print('\\n--- Step 4: Budget Verification ---')\n"
    "under_budget = final_expected <= req['budget']\n"
    "print(f\"  Budget:          ${req['budget']:,.2f}\")\n"
    "print(f\"  Expected cost:   ${final_expected:,.2f}\")\n"
    "print(f\"  {'WITHIN BUDGET' if under_budget else 'OVER BUDGET'}\")\n"
    "print(f\"  Savings vs baseline: ${baseline_cost - final_expected:,.2f} \"\n"
    "      f\"({(baseline_cost - final_expected)/baseline_cost*100:.1f}%)\")\n"
    "\n"
    "print('\\n' + '=' * 60)\n"
    "print('STRATEGY SUMMARY')\n"
    "print('=' * 60)\n"
    "print(f\"  1. Use {opt_gpu} GPUs instead of {req['gpu_count']} (optimal scaling efficiency)\")\n"
    "print(f\"  2. Enable Mixed Precision (AMP) -> ~25% faster, same accuracy\")\n"
    "print(f\"  3. Partial Spot usage for eval phase -> ~35% savings on that phase\")\n"
    "print(f\"  4. Gradient checkpointing -> reduce memory, allow larger batch\")\n"
    "print(f\"  Combined: ${baseline_cost:,.2f} -> ${final_expected:,.2f} \"\n"
    "      f\"({'WITHIN' if under_budget else 'OVER'} ${req['budget']:,.2f} budget)\")\n"
)

# ── Patch the notebook ────────────────────────────────────────────────────────
with open(NB_PATH, encoding="utf-8") as f:
    nb = json.load(f)

PATCHES = {37: CELL_37, 38: CELL_38, 39: CELL_39, 40: CELL_40, 41: CELL_41}

for idx, new_source in PATCHES.items():
    nb["cells"][idx]["source"] = new_source
    nb["cells"][idx]["outputs"] = []
    nb["cells"][idx]["execution_count"] = None
    print(f"Patched cell {idx}: {new_source.splitlines()[0][:60]}")

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("\nNotebook saved successfully.")
